apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainserver-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1  # Keep only one old Replica Set as backup
  selector:
    matchLabels:
      app: mainserver
  template:
    metadata:
      labels:
        app: mainserver
    spec:
      containers:
      - name: mainserver
        image: ghcr.io/2024-sdm-group5/mainserver-service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: github-registry
