apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainserver-service
spec:
  replicas: 6
  revisionHistoryLimit: 1  # Keep only one old Replica Set as backup
  selector:
    matchLabels:
      app: mainserver
  template:
    metadata:
      labels:
        app: mainserver
    spec:
      containers:
        - name: mainserver
          image: ghcr.io/2024-sdm-group5/mainserver-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1000m"
              memory: "1000Mi"
            limits:
              cpu: "2000m"
              memory: "2000Mi"
          env:  # 注意縮排
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: DATABASE_URL
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: GOOGLE_MAPS_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: OPENAI_API_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: REDIS_URL
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: GOOGLE_APPLICATION_CREDENTIALS
      imagePullSecrets:
        - name: github-registry
